fastfetch

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

bindkey -e

HISTSIZE=100000
HISTFILE="$XDG_CACHE_HOME/zsh/history"
SAVEHIST=$HISTSIZE
HISTUP=erase

setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt hist_find_no_dups
setopt interactive_comments
setopt autocd
setopt nobeep
setopt numeric_glob_sort

[ -s "${XDG_CONFIG_HOME}/shell/platform.zshrc" ] && source "${XDG_CONFIG_HOME}/shell/platform.zshrc"
source "${XDG_CONFIG_HOME}/shell/zim.sh"
source "${XDG_CONFIG_HOME}/shell/alias.sh"
source "${XDG_CONFIG_HOME}/shell/fzf.sh"
source "${XDG_CONFIG_HOME}/shell/init.zsh"
export PATH="$HOME/.local/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
